// ==================== КАТЕГОРИИ ====================
const CATEGORIES = {
  cpu:         { name: "Процессоры",            icon: "🔲" },
  motherboard: { name: "Материнские платы",     icon: "🟩" },
  gpu:         { name: "Видеокарты",            icon: "🎮" },
  ram:         { name: "Оперативная память",    icon: "💾" },
  storage:     { name: "Накопители",            icon: "💿" },
  psu:         { name: "Блоки питания",         icon: "🔌" },
  case:        { name: "Корпуса",               icon: "📦" },
  cooler:      { name: "Охлаждение",            icon: "❄️" },
  monitor:     { name: "Мониторы",              icon: "🖥️" },
  smartphone:  { name: "Смартфоны",             icon: "📱" },
  tablet:      { name: "Планшеты",              icon: "📲" },
  laptop:      { name: "Ноутбуки",              icon: "💻" },
  tv:          { name: "Телевизоры",            icon: "📺" },
  headphones:  { name: "Наушники",              icon: "🎧" },
  keyboard:    { name: "Клавиатуры",            icon: "⌨️" },
  mouse:       { name: "Мыши",                  icon: "🖱️" },
  console:     { name: "Игровые приставки",     icon: "🎮" },
  smartwatch:  { name: "Умные часы",            icon: "⌚" },
  camera:      { name: "Фото и видео",          icon: "📷" },
  network:     { name: "Сетевое оборудование",  icon: "📡" }
};

// ==================== ТОВАРЫ ====================
const PRODUCTS = [
  // ==================== ПРОЦЕССОРЫ (INTEL) ====================
  { id: 1, name: "Intel Core i9-14900K", category: "cpu", brand: "Intel", price: 62990, socket: "LGA1700", tdp: 253,
    img: "img/real/cpu/i9_14900k.webp",
    specs: { "Ядер": 24, "Потоков": 32, "Частота": "3.2–6.0 ГГц", "Кэш L3": "36 МБ", "TDP": "253 Вт" } },
  { id: 2, name: "Intel Core i9-13900K", category: "cpu", brand: "Intel", price: 52990, socket: "LGA1700", tdp: 253,
    img: "img/real/cpu/i9_13900k.webp",
    specs: { "Ядер": 24, "Потоков": 32, "Частота": "3.0–5.8 ГГц", "TDP": "253 Вт" } },
  { id: 3, name: "Intel Core i7-14700K", category: "cpu", brand: "Intel", price: 42990, socket: "LGA1700", tdp: 253,
    img: "img/real/cpu/i7_14700k.webp",
    specs: { "Ядер": 20, "Потоков": 28, "Частота": "3.4–5.6 ГГц" } },
  { id: 4, name: "Intel Core i7-13700K", category: "cpu", brand: "Intel", price: 36990, socket: "LGA1700", tdp: 253,
    img: "img/real/cpu/i7_13700k.webp",
    specs: { "Ядер": 16, "Потоков": 24, "Частота": "3.4–5.4 ГГц" } },
  { id: 5, name: "Intel Core i5-14600KF", category: "cpu", brand: "Intel", price: 28990, socket: "LGA1700", tdp: 181,
    img: "img/real/cpu/i5_14600kf.webp",
    specs: { "Ядер": 14, "Потоков": 20, "Частота": "3.5–5.3 ГГц" } },
  { id: 6, name: "Intel Core i5-13400F", category: "cpu", brand: "Intel", price: 18990, socket: "LGA1700", tdp: 148,
    img: "img/real/cpu/i5_13400f.webp",
    specs: { "Ядер": 10, "Потоков": 16, "Частота": "2.5–4.6 ГГц" } },
  { id: 7, name: "Intel Core i3-13100F", category: "cpu", brand: "Intel", price: 10990, socket: "LGA1700", tdp: 89,
    img: "img/real/cpu/i3_13100f.webp",
    specs: { "Ядер": 4, "Потоков": 8, "Частота": "3.4–4.5 ГГц" } },

  // ==================== ПРОЦЕССОРЫ (AMD) ====================
  { id: 10, name: "AMD Ryzen 9 7950X", category: "cpu", brand: "AMD", price: 58990, socket: "AM5", tdp: 170,
    img: "img/real/cpu/ryzen_9_7950x.webp",
    specs: { "Ядер": 16, "Потоков": 32, "Частота": "4.5–5.7 ГГц", "Кэш L3": "64 МБ" } },
  { id: 11, name: "AMD Ryzen 9 7900X", category: "cpu", brand: "AMD", price: 44990, socket: "AM5", tdp: 170,
    img: "img/real/cpu/ryzen_9_7900x.webp",
    specs: { "Ядер": 12, "Потоков": 24, "Частота": "4.7–5.6 ГГц" } },
  { id: 12, name: "AMD Ryzen 7 7800X3D", category: "cpu", brand: "AMD", price: 41990, socket: "AM5", tdp: 120,
    img: "img/real/cpu/ryzen_7_7800x3d.webp",
    specs: { "Ядер": 8, "Потоков": 16, "Частота": "4.2–5.0 ГГц", "3D V-Cache": "96 МБ" } },
  { id: 13, name: "AMD Ryzen 7 7700X", category: "cpu", brand: "AMD", price: 29990, socket: "AM5", tdp: 105,
    img: "img/real/cpu/ryzen_7_7700x.webp",
    specs: { "Ядер": 8, "Потоков": 16, "Частота": "4.5–5.4 ГГц" } },
  { id: 14, name: "AMD Ryzen 5 7600X", category: "cpu", brand: "AMD", price: 21990, socket: "AM5", tdp: 105,
    img: "img/real/cpu/ryzen_5_7600x.webp",
    specs: { "Ядер": 6, "Потоков": 12, "Частота": "4.7–5.3 ГГц" } },
  { id: 15, name: "AMD Ryzen 5 5600", category: "cpu", brand: "AMD", price: 11990, socket: "AM4", tdp: 65,
    img: "img/real/cpu/ryzen_5_5600.webp",
    specs: { "Ядер": 6, "Потоков": 12, "Частота": "3.5–4.4 ГГц" } },

  // ==================== МАТЕРИНСКИЕ ПЛАТЫ ====================
  { id: 20, name: "ASUS ROG STRIX Z790-E Gaming", category: "motherboard", brand: "ASUS", price: 45990, socket: "LGA1700", img: "img/real/motherboard/asus_z790e.webp",
    specs: { "Чипсет": "Z790", "Форм-фактор": "ATX", "RAM": "DDR5, 4 слота", "M.2": "4 шт" } },
  { id: 21, name: "ASUS TUF Gaming B760-PLUS", category: "motherboard", brand: "ASUS", price: 18990, socket: "LGA1700", img: "img/real/motherboard/asus_b760_tuf.webp",
    specs: { "Чипсет": "B760", "Форм-фактор": "ATX", "RAM": "DDR5" } },
  { id: 22, name: "MSI MAG B650 TOMAHAWK WiFi", category: "motherboard", brand: "MSI", price: 24990, socket: "AM5", img: "img/real/motherboard/msi_b650_tomahawk.webp",
    specs: { "Чипсет": "B650", "Форм-фактор": "ATX", "RAM": "DDR5" } },
  { id: 23, name: "MSI MPG X670E Carbon WiFi", category: "motherboard", brand: "MSI", price: 42990, socket: "AM5", img: "img/real/motherboard/msi_x670e_carbon.webp",
    specs: { "Чипсет": "X670E", "Форм-фактор": "ATX", "RAM": "DDR5" } },
  { id: 24, name: "Gigabyte B760M DS3H", category: "motherboard", brand: "Gigabyte", price: 12990, socket: "LGA1700", img: "img/real/motherboard/gigabyte_b760m.webp",
    specs: { "Чипсет": "B760", "Форм-фактор": "mATX" } },
  { id: 25, name: "ASRock B550M Pro4", category: "motherboard", brand: "ASRock", price: 9990, socket: "AM4", img: "img/real/motherboard/asrock_b550m.webp",
    specs: { "Чипсет": "B550", "Форм-фактор": "mATX" } },
  { id: 26, name: "Asus Prime Z790-A WiFi", category: "motherboard", brand: "ASUS", price: 32990, socket: "LGA1700", img: "img/real/motherboard/asus_prime_z790a.webp",
    specs: { "Чипсет": "Z790", "Форм-фактор": "ATX" } },

  // ==================== ВИДЕОКАРТЫ ====================
  { id: 30, name: "NVIDIA GeForce RTX 4090 24GB", category: "gpu", brand: "NVIDIA", price: 189990, tdp: 450, img: "img/real/gpu/rtx_4090.webp",
    specs: { "Память": "24 ГБ GDDR6X", "Частота": "2.23–2.52 ГГц", "Питание": "450 Вт" } },
  { id: 31, name: "NVIDIA GeForce RTX 4080 Super", category: "gpu", brand: "NVIDIA", price: 119990, tdp: 320, img: "img/real/gpu/rtx_4080_super.webp",
    specs: { "Память": "16 ГБ GDDR6X" } },
  { id: 32, name: "NVIDIA GeForce RTX 4070 Ti Super", category: "gpu", brand: "NVIDIA", price: 89990, tdp: 285, img: "img/real/gpu/rtx_4070_ti_super.webp",
    specs: { "Память": "16 ГБ GDDR6X" } },
  { id: 33, name: "NVIDIA GeForce RTX 4070 Super", category: "gpu", brand: "NVIDIA", price: 69990, tdp: 220, img: "img/real/gpu/rtx_4070_super.webp",
    specs: { "Память": "12 ГБ GDDR6X" } },
  { id: 34, name: "NVIDIA GeForce RTX 4060 Ti 16GB", category: "gpu", brand: "NVIDIA", price: 52990, tdp: 165, img: "img/real/gpu/rtx_4060_ti.webp",
    specs: { "Память": "16 ГБ GDDR6" } },
  { id: 35, name: "NVIDIA GeForce RTX 4060 8GB", category: "gpu", brand: "NVIDIA", price: 34990, tdp: 115, img: "img/real/gpu/rtx_4060.webp",
    specs: { "Память": "8 ГБ GDDR6" } },
  { id: 36, name: "NVIDIA GeForce RTX 3060 12GB", category: "gpu", brand: "NVIDIA", price: 26990, tdp: 170, img: "img/real/gpu/rtx_3060.webp",
    specs: { "Память": "12 ГБ GDDR6" } },
  { id: 37, name: "AMD Radeon RX 7900 XTX", category: "gpu", brand: "AMD", price: 109990, tdp: 355, img: "img/real/gpu/rx_7900_xtx.webp",
    specs: { "Память": "24 ГБ GDDR6" } },
  { id: 38, name: "AMD Radeon RX 7800 XT", category: "gpu", brand: "AMD", price: 64990, tdp: 263, img: "img/real/gpu/rx_7800_xt.webp",
    specs: { "Память": "16 ГБ GDDR6" } },
  { id: 39, name: "AMD Radeon RX 7600", category: "gpu", brand: "AMD", price: 29990, tdp: 165, img: "img/real/gpu/rx_7600.webp",
    specs: { "Память": "8 ГБ GDDR6" } },

  // ==================== ОПЕРАТИВНАЯ ПАМЯТЬ ====================
  { id: 50, name: "Kingston Fury Beast DDR5 32GB (2×16) 6000", category: "ram", brand: "Kingston", price: 12990, ramType: "DDR5", img: "img/real/ram/kingston_ddr5_32gb.webp",
    specs: { "Объём": "32 ГБ", "Тип": "DDR5", "Частота": "6000 МГц", "Комплект": "2×16 ГБ" } },
  { id: 51, name: "Corsair Vengeance DDR5 64GB (2×32) 5600", category: "ram", brand: "Corsair", price: 24990, ramType: "DDR5", img: "img/real/ram/corsair_ddr5_64gb.webp",
    specs: { "Объём": "64 ГБ", "Тип": "DDR5" } },
  { id: 52, name: "G.Skill Trident Z5 RGB DDR5 32GB 6400", category: "ram", brand: "G.Skill", price: 15990, ramType: "DDR5", img: "img/real/ram/gskill_ddr5_32gb.webp",
    specs: { "Объём": "32 ГБ", "Тип": "DDR5" } },
  { id: 53, name: "G.Skill Ripjaws V DDR4 16GB (2×8) 3200", category: "ram", brand: "G.Skill", price: 5990, ramType: "DDR4", img: "img/real/ram/gskill_ddr4_16gb.webp",
    specs: { "Объём": "16 ГБ", "Тип": "DDR4" } },
  { id: 54, name: "Kingston Fury DDR4 32GB (2×16) 3600", category: "ram", brand: "Kingston", price: 9990, ramType: "DDR4", img: "img/real/ram/kingston_ddr4_32gb.webp",
    specs: { "Объём": "32 ГБ", "Тип": "DDR4" } },
  { id: 55, name: "Patriot Viper Steel DDR4 16GB 3600", category: "ram", brand: "Patriot", price: 5490, ramType: "DDR4", img: "img/real/ram/patriot_ddr4_16gb.webp",
    specs: { "Объём": "16 ГБ", "Тип": "DDR4" } },

  // ==================== НАКОПИТЕЛИ ====================
  { id: 60, name: "Samsung 990 Pro 2TB NVMe PCIe 4.0", category: "storage", brand: "Samsung", price: 19990, img: "img/real/storage/samsung_990_pro_2tb.webp",
    specs: { "Объём": "2 ТБ", "Интерфейс": "PCIe 4.0", "Скорость чтения": "7450 МБ/с" } },
  { id: 61, name: "Samsung 980 Pro 1TB NVMe", category: "storage", brand: "Samsung", price: 11990, img: "img/real/storage/samsung_980_pro_1tb.webp",
    specs: { "Объём": "1 ТБ", "Интерфейс": "PCIe 4.0" } },
  { id: 62, name: "WD Black SN850X 2TB", category: "storage", brand: "WD", price: 17990, img: "img/real/storage/wd_sn850x_2tb.webp",
    specs: { "Объём": "2 ТБ", "Интерфейс": "PCIe 4.0" } },
  { id: 63, name: "Kingston KC3000 1TB NVMe", category: "storage", brand: "Kingston", price: 9990, img: "img/real/storage/kingston_kc3000_1tb.webp",
    specs: { "Объём": "1 ТБ" } },
  { id: 64, name: "Seagate Barracuda 4TB HDD", category: "storage", brand: "Seagate", price: 8990, img: "img/real/storage/seagate_barracuda_4tb.webp",
    specs: { "Объём": "4 ТБ", "Интерфейс": "SATA III" } },
  { id: 65, name: "WD Blue 2TB HDD", category: "storage", brand: "WD", price: 5990, img: "img/real/storage/wd_blue_2tb.webp",
    specs: { "Объём": "2 ТБ" } },
  { id: 66, name: "Crucial P3 Plus 500GB NVMe", category: "storage", brand: "Crucial", price: 4490, img: "img/real/storage/crucial_p3_500gb.webp",
    specs: { "Объём": "500 ГБ" } },

  // ==================== БЛОКИ ПИТАНИЯ ====================
  { id: 70, name: "be quiet! Dark Power 13 1000W", category: "psu", brand: "be quiet!", price: 22990, power: 1000, img: "img/real/psu/bequiet_dark_power_1000w.webp",
    specs: { "Мощность": "1000 Вт", "Сертификат": "80+ Titanium" } },
  { id: 71, name: "Corsair RM850x 850W Gold", category: "psu", brand: "Corsair", price: 14990, power: 850, img: "img/real/psu/corsair_rm850x.webp",
    specs: { "Мощность": "850 Вт", "Сертификат": "80+ Gold" } },
  { id: 72, name: "Seasonic Focus GX-750 750W", category: "psu", brand: "Seasonic", price: 11990, power: 750, img: "img/real/psu/seasonic_focus_gx750.webp",
    specs: { "Мощность": "750 Вт" } },
  { id: 73, name: "Cooler Master MWE 650 Bronze", category: "psu", brand: "Cooler Master", price: 5990, power: 650, img: "img/real/psu/coolermaster_mwe650.webp",
    specs: { "Мощность": "650 Вт" } },
  { id: 74, name: "Chieftec Polaris 550W Bronze", category: "psu", brand: "Chieftec", price: 4490, power: 550, img: "img/real/psu/chieftec_polaris_550w.webp",
    specs: { "Мощность": "550 Вт" } },

  // ==================== КОРПУСА ====================
  { id: 80, name: "NZXT H7 Flow White", category: "case", brand: "NZXT", price: 12990, img: "img/real/case/nzxt_h7_flow.webp",
    specs: { "Форм-фактор": "Mid-Tower" } },
  { id: 81, name: "Lian Li O11 Dynamic EVO", category: "case", brand: "Lian Li", price: 15990, img: "img/real/case/lianli_o11_dynamic.webp",
    specs: { "Форм-фактор": "Mid-Tower" } },
  { id: 82, name: "Fractal Design Meshify 2", category: "case", brand: "Fractal", price: 13990, img: "img/real/case/fractal_meshify_2.webp",
    specs: { "Форм-фактор": "Mid-Tower" } },
  { id: 83, name: "Cooler Master MasterBox TD500", category: "case", brand: "Cooler Master", price: 8990, img: "img/real/case/coolermaster_td500.webp",
    specs: { "Форм-фактор": "Mid-Tower" } },
  { id: 84, name: "Zalman i3 Neo Black", category: "case", brand: "Zalman", price: 3490, img: "img/real/case/zalman_i3_neo.webp",
    specs: { "Форм-фактор": "Mid-Tower" } },

  // ==================== ОХЛАЖДЕНИЕ ====================
  { id: 90, name: "Noctua NH-D15 Chromax Black", category: "cooler", brand: "Noctua", price: 12990, img: "img/real/cooler/noctua_nhd15.webp",
    specs: { "Тип": "Кулер", "TDP": "220 Вт" } },
  { id: 91, name: "NZXT Kraken Elite 360 RGB", category: "cooler", brand: "NZXT", price: 29990, img: "img/real/cooler/nzxt_kraken_360.webp",
    specs: { "Тип": "СЖО 360 мм" } },
  { id: 92, name: "DeepCool AK620", category: "cooler", brand: "DeepCool", price: 6490, img: "img/real/cooler/deepcool_ak620.webp",
    specs: { "Тип": "Кулер" } },
  { id: 93, name: "Arctic Liquid Freezer III 240", category: "cooler", brand: "Arctic", price: 8990, img: "img/real/cooler/arctic_lf3_240.webp",
    specs: { "Тип": "СЖО 240 мм" } },
  { id: 94, name: "be quiet! Pure Rock 2", category: "cooler", brand: "be quiet!", price: 3990, img: "img/real/cooler/bequiet_pure_rock_2.webp",
    specs: { "Тип": "Кулер" } },

  // ==================== СМАРТФОНЫ ====================
  { id: 100, name: "Apple iPhone 15 Pro Max 256GB", category: "smartphone", brand: "Apple", price: 129990, img: "img/real/smartphone/iphone_15_pro_max.webp",
    specs: { "Экран": "6.7\" OLED 120 Гц", "Процессор": "A17 Pro", "Камера": "48+12+12 Мп" } },
  { id: 101, name: "Apple iPhone 15 128GB", category: "smartphone", brand: "Apple", price: 79990, img: "img/real/smartphone/iphone_15.webp",
    specs: { "Экран": "6.1\" OLED", "Процессор": "A16 Bionic" } },
  { id: 102, name: "Apple iPhone 14 128GB", category: "smartphone", brand: "Apple", price: 62990, img: "img/real/smartphone/iphone_14.webp",
    specs: { "Экран": "6.1\" OLED" } },
  { id: 103, name: "Samsung Galaxy S24 Ultra 512GB", category: "smartphone", brand: "Samsung", price: 139990, img: "img/real/smartphone/galaxy_s24_ultra.webp",
    specs: { "Экран": "6.8\" AMOLED", "Камера": "200 Мп" } },
  { id: 104, name: "Samsung Galaxy S24+ 256GB", category: "smartphone", brand: "Samsung", price: 89990, img: "img/real/smartphone/galaxy_s24_plus.webp",
    specs: { "Экран": "6.7\" AMOLED" } },
  { id: 105, name: "Samsung Galaxy A55 5G 128GB", category: "smartphone", brand: "Samsung", price: 29990, img: "img/real/smartphone/galaxy_a55.webp",
    specs: { "Экран": "6.6\" AMOLED" } },
  { id: 106, name: "Xiaomi 14 Ultra 512GB", category: "smartphone", brand: "Xiaomi", price: 99990, img: "img/real/smartphone/xiaomi_14_ultra.webp",
    specs: { "Камера": "50 Мп Leica" } },
  { id: 107, name: "Xiaomi Redmi Note 13 Pro+", category: "smartphone", brand: "Xiaomi", price: 29990, img: "img/real/smartphone/redmi_note_13_pro.webp",
    specs: { "Экран": "6.67\" AMOLED" } },
  { id: 108, name: "Xiaomi Redmi Note 12 128GB", category: "smartphone", brand: "Xiaomi", price: 15990, img: "img/real/smartphone/redmi_note_12.webp",
    specs: { "Экран": "6.67\"" } },
  { id: 109, name: "Google Pixel 8 Pro 128GB", category: "smartphone", brand: "Google", price: 89990, img: "img/real/smartphone/pixel_8_pro.webp",
    specs: { "Процессор": "Tensor G3" } },
  { id: 110, name: "Google Pixel 8 128GB", category: "smartphone", brand: "Google", price: 62990, img: "img/real/smartphone/pixel_8.webp",
    specs: { "Экран": "6.2\" OLED" } },
  { id: 111, name: "Huawei P60 Pro 256GB", category: "smartphone", brand: "Huawei", price: 74990, img: "img/real/smartphone/huawei_p60_pro.webp",
    specs: { "Экран": "6.67\" OLED" } },
  { id: 112, name: "OnePlus 12 256GB", category: "smartphone", brand: "OnePlus", price: 69990, img: "img/real/smartphone/oneplus_12.webp",
    specs: { "Экран": "6.82\" AMOLED" } },
  { id: 113, name: "realme GT 5 Pro 256GB", category: "smartphone", brand: "realme", price: 54990, img: "img/real/smartphone/realme_gt5_pro.webp",
    specs: { "Экран": "6.78\" AMOLED" } },
  { id: 114, name: "Tecno Camon 20 Pro", category: "smartphone", brand: "Tecno", price: 16990, img: "img/real/smartphone/tecno_camon_20.webp",
    specs: { "Экран": "6.67\" AMOLED" } },
  { id: 115, name: "Nothing Phone (2) 256GB", category: "smartphone", brand: "Nothing", price: 44990, img: "img/real/smartphone/nothing_phone_2.webp",
    specs: { "Экран": "6.7\" LTPO OLED" } },

  // ==================== ПЛАНШЕТЫ ====================
  { id: 120, name: "Apple iPad Pro 12.9\" M2 256GB", category: "tablet", brand: "Apple", price: 119990, img: "img/real/tablet/ipad_pro_12_9.webp",
    specs: { "Экран": "12.9\" Liquid Retina", "Процессор": "M2" } },
  { id: 121, name: "Apple iPad Air 5 64GB", category: "tablet", brand: "Apple", price: 54990, img: "img/real/tablet/ipad_air_5.webp",
    specs: { "Экран": "10.9\"", "Процессор": "M1" } },
  { id: 122, name: "Samsung Galaxy Tab S9 Ultra", category: "tablet", brand: "Samsung", price: 109990, img: "img/real/tablet/galaxy_tab_s9_ultra.webp",
    specs: { "Экран": "14.6\" AMOLED" } },
  { id: 123, name: "Xiaomi Pad 6 128GB", category: "tablet", brand: "Xiaomi", price: 24990, img: "img/real/tablet/xiaomi_pad_6.webp",
    specs: { "Экран": "11\" 144 Гц" } },
  { id: 124, name: "Huawei MatePad 11.5", category: "tablet", brand: "Huawei", price: 27990, img: "img/real/tablet/huawei_matepad_11.webp",
    specs: { "Экран": "11.5\" 120 Гц" } },

   // ==================== НОУТБУКИ ====================
  { id: 130, name: "Apple MacBook Pro 16\" M3 Pro", category: "laptop", brand: "Apple", price: 249990, img: "img/real/laptop/macbook_pro_16.webp",
    specs: { "Процессор": "M3 Pro", "RAM": "18 ГБ", "SSD": "512 ГБ" } },
  { id: 131, name: "Apple MacBook Air 13\" M2", category: "laptop", brand: "Apple", price: 109990, img: "img/real/laptop/macbook_air_13.webp",
    specs: { "Процессор": "M2", "RAM": "8 ГБ" } },
  { id: 132, name: "ASUS ROG Zephyrus G14 (2024)", category: "laptop", brand: "ASUS", price: 189990, img: "img/real/laptop/asus_rog_zephyrus_g14.webp",
    specs: { "CPU": "Ryzen 9", "GPU": "RTX 4070" } },
  { id: 133, name: "ASUS TUF Gaming A15", category: "laptop", brand: "ASUS", price: 89990, img: "img/real/laptop/asus_tuf_a15.webp",
    specs: { "GPU": "RTX 4060" } },
  { id: 134, name: "Lenovo Legion Pro 5", category: "laptop", brand: "Lenovo", price: 129990, img: "img/real/laptop/lenovo_legion_pro_5.webp",
    specs: { "GPU": "RTX 4060" } },
  { id: 135, name: "HP Pavilion 15", category: "laptop", brand: "HP", price: 54990, img: "img/real/laptop/hp_pavilion_15.webp",
    specs: { "CPU": "i5-1235U" } },
  { id: 136, name: "Acer Nitro 5", category: "laptop", brand: "Acer", price: 74990, img: "img/real/laptop/acer_nitro_5.webp",
    specs: { "GPU": "RTX 4050" } },
  { id: 137, name: "Huawei MateBook D16", category: "laptop", brand: "Huawei", price: 69990, img: "img/real/laptop/huawei_matebook_d16.webp",
    specs: { "CPU": "i5-12450H" } },
  { id: 138, name: "MSI Katana 15", category: "laptop", brand: "MSI", price: 84990, img: "img/real/laptop/msi_katana_15.webp",
    specs: { "GPU": "RTX 4050" } },
  { id: 139, name: "Honor MagicBook X16 Pro", category: "laptop", brand: "Honor", price: 59990, img: "img/real/laptop/honor_magicbook_x16.webp",
    specs: { "CPU": "i5-13500H" } },

    // ==================== МОНИТОРЫ ====================
  { id: 150, name: "Samsung Odyssey G7 32\" 240Hz", category: "monitor", brand: "Samsung", price: 54990, img: "img/real/monitor/samsung_odyssey_g7.webp",
    specs: { "Диагональ": "32\"", "Частота": "240 Гц" } },
  { id: 151, name: "LG UltraGear 27GP850 27\"", category: "monitor", brand: "LG", price: 32990, img: "img/real/monitor/lg_ultragear_27gp850.webp",
    specs: { "Диагональ": "27\"", "Частота": "165 Гц" } },
  { id: 152, name: "ASUS ROG Swift PG279QM", category: "monitor", brand: "ASUS", price: 79990, img: "img/real/monitor/asus_rog_swift_pg279qm.webp",
    specs: { "Диагональ": "27\"", "Частота": "240 Гц" } },
  { id: 153, name: "Dell UltraSharp U2723QE 27\" 4K", category: "monitor", brand: "Dell", price: 64990, img: "img/real/monitor/dell_ultrasharp_u2723qe.webp",
    specs: { "Разрешение": "3840×2160" } },
  { id: 154, name: "AOC 24G2SPU 24\" 165Hz", category: "monitor", brand: "AOC", price: 17990, img: "img/real/monitor/aoc_24g2spu.webp",
    specs: { "Частота": "165 Гц" } },
  { id: 155, name: "MSI Optix MAG274QRF-QD", category: "monitor", brand: "MSI", price: 44990, img: "img/real/monitor/msi_optix_mag274.webp",
    specs: { "Разрешение": "2560×1440" } },

  // ==================== ТЕЛЕВИЗОРЫ ====================
  { id: 160, name: "Samsung QE55Q70C 55\" QLED 4K", category: "tv", brand: "Samsung", price: 89990, img: "img/real/tv/samsung_qe55q70c.webp",
    specs: { "Диагональ": "55\"", "Технология": "QLED" } },
  { id: 161, name: "LG OLED55C3 55\" OLED 4K", category: "tv", brand: "LG", price: 129990, img: "img/real/tv/lg_oled55c3.webp",
    specs: { "Технология": "OLED" } },
  { id: 162, name: "Sony Bravia XR-55A80L 55\" OLED", category: "tv", brand: "Sony", price: 159990, img: "img/real/tv/sony_bravia_a80l.webp",
    specs: { "Диагональ": "55\"" } },
  { id: 163, name: "Xiaomi TV A2 43\"", category: "tv", brand: "Xiaomi", price: 29990, img: "img/real/tv/xiaomi_tv_a2_43.webp",
    specs: { "Диагональ": "43\"" } },
  { id: 164, name: "Hisense 65U8KQ 65\" Mini-LED", category: "tv", brand: "Hisense", price: 119990, img: "img/real/tv/hisense_65u8kq.webp",
    specs: { "Диагональ": "65\"" } },

    // ==================== НАУШНИКИ ====================
  { id: 170, name: "Sony WH-1000XM5", category: "headphones", brand: "Sony", price: 34990, img: "img/real/headphones/sony_wh1000xm5.webp",
    specs: { "Тип": "Накладные", "ANC": "Да" } },
  { id: 171, name: "Apple AirPods Pro 2 USB-C", category: "headphones", brand: "Apple", price: 24990, img: "img/real/headphones/airpods_pro_2.webp",
    specs: { "Тип": "TWS" } },
  { id: 172, name: "Bose QuietComfort Ultra", category: "headphones", brand: "Bose", price: 42990, img: "img/real/headphones/bose_qc_ultra.webp",
    specs: { "Тип": "Накладные" } },
  { id: 173, name: "JBL Tune 770NC", category: "headphones", brand: "JBL", price: 9990, img: "img/real/headphones/jbl_tune_770nc.webp",
    specs: { "ANC": "Да" } },
  { id: 174, name: "HyperX Cloud III", category: "headphones", brand: "HyperX", price: 12990, img: "img/real/headphones/hyperx_cloud_3.webp",
    specs: { "Тип": "Игровые" } },
  { id: 175, name: "Marshall Major V", category: "headphones", brand: "Marshall", price: 19990, img: "img/real/headphones/marshall_major_v.webp",
    specs: { "Тип": "Накладные" } },
  { id: 176, name: "Samsung Galaxy Buds2 Pro", category: "headphones", brand: "Samsung", price: 16990, img: "img/real/headphones/galaxy_buds2_pro.webp",
    specs: { "TWS": "Да" } },

    // ==================== КЛАВИАТУРЫ ====================
  { id: 180, name: "HyperX Alloy Origins Red", category: "keyboard", brand: "HyperX", price: 9990, img: "img/real/keyboard/hyperx_alloy_origins.webp",
    specs: { "Тип": "Механическая" } },
  { id: 181, name: "Logitech MX Keys S", category: "keyboard", brand: "Logitech", price: 11990, img: "img/real/keyboard/logitech_mx_keys_s.webp",
    specs: { "Тип": "Мембранная" } },
  { id: 182, name: "Keychron K8 Pro", category: "keyboard", brand: "Keychron", price: 12990, img: "img/real/keyboard/keychron_k8_pro.webp",
    specs: { "Тип": "Механическая" } },
  { id: 183, name: "Razer BlackWidow V4", category: "keyboard", brand: "Razer", price: 14990, img: "img/real/keyboard/razer_blackwidow_v4.webp",
    specs: { "Тип": "Механическая" } },
  { id: 184, name: "Ducky One 3 TKL", category: "keyboard", brand: "Ducky", price: 15990, img: "img/real/keyboard/ducky_one_3.webp",
    specs: { "Тип": "Механическая" } },

   // ==================== МЫШИ ====================
  { id: 190, name: "Logitech G Pro X Superlight 2", category: "mouse", brand: "Logitech", price: 14990, img: "img/real/mouse/logitech_gpx_superlight_2.webp",
    specs: { "DPI": "32000", "Вес": "60 г" } },
  { id: 191, name: "Razer DeathAdder V3 Pro", category: "mouse", brand: "Razer", price: 16990, img: "img/real/mouse/razer_deathadder_v3.webp",
    specs: { "DPI": "30000" } },
  { id: 192, name: "Logitech MX Master 3S", category: "mouse", brand: "Logitech", price: 9990, img: "img/real/mouse/logitech_mx_master_3s.webp",
    specs: { "DPI": "8000" } },
  { id: 193, name: "SteelSeries Rival 3", category: "mouse", brand: "SteelSeries", price: 3490, img: "img/real/mouse/steelseries_rival_3.webp",
    specs: { "DPI": "8500" } },

   // ==================== ИГРОВЫЕ ПРИСТАВКИ ====================
  { id: 200, name: "Sony PlayStation 5 Slim", category: "console", brand: "Sony", price: 64990, img: "img/real/console/ps5_slim.webp",
    specs: { "SSD": "1 ТБ" } },
  { id: 201, name: "Sony PlayStation 5 Pro", category: "console", brand: "Sony", price: 99990, img: "img/real/console/ps5_pro.webp",
    specs: { "SSD": "2 ТБ" } },
  { id: 202, name: "Microsoft Xbox Series X 1TB", category: "console", brand: "Microsoft", price: 59990, img: "img/real/console/xbox_series_x.webp",
    specs: { "SSD": "1 ТБ" } },
  { id: 203, name: "Microsoft Xbox Series S", category: "console", brand: "Microsoft", price: 34990, img: "img/real/console/xbox_series_s.webp",
    specs: { "SSD": "512 ГБ" } },
  { id: 204, name: "Nintendo Switch OLED", category: "console", brand: "Nintendo", price: 32990, img: "img/real/console/nintendo_switch_oled.webp",
    specs: { "Экран": "7\" OLED" } },


    // ==================== УМНЫЕ ЧАСЫ ====================
  { id: 210, name: "Apple Watch Ultra 2", category: "smartwatch", brand: "Apple", price: 89990, img: "img/real/smartwatch/apple_watch_ultra_2.webp",
    specs: { "Экран": "49 мм" } },
  { id: 211, name: "Apple Watch Series 9 45mm", category: "smartwatch", brand: "Apple", price: 44990, img: "img/real/smartwatch/apple_watch_s9.webp",
    specs: { "Экран": "45 мм" } },
  { id: 212, name: "Samsung Galaxy Watch6 Classic", category: "smartwatch", brand: "Samsung", price: 34990, img: "img/real/smartwatch/galaxy_watch6_classic.webp",
    specs: { "Экран": "1.47\"" } },
  { id: 213, name: "Huawei Watch GT 4", category: "smartwatch", brand: "Huawei", price: 19990, img: "img/real/smartwatch/huawei_watch_gt4.webp",
    specs: { "Автономность": "14 дней" } },
  { id: 214, name: "Garmin Fenix 7 Pro", category: "smartwatch", brand: "Garmin", price: 79990, img: "img/real/smartwatch/garmin_fenix_7_pro.webp",
    specs: { "GPS": "Да" } },
  { id: 215, name: "Xiaomi Smart Band 8 Pro", category: "smartwatch", brand: "Xiaomi", price: 4990, img: "img/real/smartwatch/xiaomi_band_8_pro.webp",
    specs: { "Экран": "1.74\"" } },

    // ==================== ФОТО И ВИДЕО ====================
  { id: 220, name: "Canon EOS R6 Mark II Body", category: "camera", brand: "Canon", price: 249990, img: "img/real/camera/canon_eos_r6_ii.webp",
    specs: { "Матрица": "Full Frame 24 Мп", "Видео": "4K 60p" } },
  { id: 221, name: "Sony Alpha A7 IV Body", category: "camera", brand: "Sony", price: 229990, img: "img/real/camera/sony_a7_iv.webp",
    specs: { "Матрица": "33 Мп" } },
  { id: 222, name: "Nikon Z6 II Body", category: "camera", brand: "Nikon", price: 189990, img: "img/real/camera/nikon_z6_ii.webp",
    specs: { "Матрица": "24.5 Мп" } },
  { id: 223, name: "GoPro HERO12 Black", category: "camera", brand: "GoPro", price: 39990, img: "img/real/camera/gopro_hero12.webp",
    specs: { "Видео": "5.3K 60fps" } },
  { id: 224, name: "DJI Mini 4 Pro", category: "camera", brand: "DJI", price: 89990, img: "img/real/camera/dji_mini_4_pro.webp",
    specs: { "Камера": "4K 100fps" } },

   // ==================== СЕТЕВОЕ ОБОРУДОВАНИЕ ====================
  { id: 230, name: "TP-Link Archer AX73 WiFi 6", category: "network", brand: "TP-Link", price: 9990, img: "img/real/network/tplink_archer_ax73.webp",
    specs: { "WiFi": "6 (AX5400)" } },
  { id: 231, name: "ASUS RT-AX88U Pro", category: "network", brand: "ASUS", price: 24990, img: "img/real/network/asus_rt_ax88u.webp",
    specs: { "WiFi": "6 (AX6000)" } },
  { id: 232, name: "Keenetic Giga (KN-1011)", category: "network", brand: "Keenetic", price: 11990, img: "img/real/network/keenetic_giga.webp",
    specs: { "WiFi": "5 (AC2600)" } },
  { id: 233, name: "MikroTik hAP ax3", category: "network", brand: "MikroTik", price: 12990, img: "img/real/network/mikrotik_hap_ax3.webp",
    specs: { "WiFi": "6" } }
 ]; 